theme: jekyll-theme-time-machine
title: zupan
description: Let's create a community owned TikTok clone !
idea:
  question: Like the idea ?
  link: https://tinyurl.com/zupan-form
  title: Fill the form !
social:
  instagram: https://www.instagram.com/zupan_app/
contact:
  link: https://lilybucher.com
  title: Lily Bucher
