theme: jekyll-theme-time-machine
title: zupan
description: A community owned TikTok clone
idea:
  question: Like the idea ?
  answer: Follow
  link: https://www.instagram.com/zupan_app
  image: <img src="/assets/insta.png" class="link"/>
help:
  question: You can help ?
  answer: Fill the form
  link: https://tinyurl.com/zupan-form
  image: <img src="/assets/form.png" class="link"/>
follow:
contact:
  link: https://lilybucher.com
  title: Lily Bucher
