theme: jekyll-theme-time-machine
title: zupan
description: Let's create a community owned TikTok clone !
idea:
  question: Like the idea ?
help:
  link: https://tinyurl.com/zupan-form
  title: Fill the form !
follow:
  link: https://www.instagram.com/zupan_app
  title: Follow
  image: <img src="/assets/insta.png" class="insta"/>
contact:
  link: https://lilybucher.com
  title: Lily Bucher
